matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      script: cd scripts && npm i && node ./link-demo-dev.js && cd ../src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-ng && npm run ci.tslint
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode11.7
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      before_install: pip install six
      script: cd demo && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install:
        - nvm install 10
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      script: cd demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-28
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
licenses:
    - 'android-sdk-license-.+'

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable